version: '3.8'
services:
  sd-api:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./models:/models
      - ./output:/output
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
