services:
  sd-api:
    build:
      context: .
      args:
        PORT: 8000
    environment:
      - PORT=8000
      - LOG_LEVEL=info
      # - SD_MODEL=runwayml/stable-diffusion-v1-5
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
      - ./output:/output
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
